#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"   # Directory of this script
FILE="${SCRIPTDIR}/data/files/83-Bi-209g.jeff33"
FILENAME="$(basename $FILE)"
DIR="TEST-NJOY"
mkdir -p "$DIR"
(
cd "$DIR" &&
"${SCRIPTDIR}/run-njoy" "${FILE}"  --covr  --messages  --prefix "${FILENAME%.*}" \
                                   --keependf --toler 0.1  --iwt 6
)
