#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"   # Directory of this script
FILE="${SCRIPTDIR}/data/files/83-Bi-209g.jeff33"
FILENAME="$(basename $FILE)"
DIR="TEST-PREPRO"
mkdir -p "$DIR"
(
cd "$DIR" &&
"${SCRIPTDIR}/run-prepro" "${FILE}" --prefix PrePro --keependf --messages 
)
